### ISSUE TITLE
Finished project returning error & not firing IFTTT trigger

### ISSUE THREAD

**Issue by mrkeyes** [sedgett/OctoPrint_IFTTTmaker#4]
It looks like it's not firing the IFTTT command when octoprint is done printing. I've got this error from the log. Any help would be appreciated!
`INFO - Finished in 17155.989 s.
2017-10-01 08:19:37,916 - octoprint.plugin - ERROR - Error while calling plugin IFTTTmaker
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTTmaker/__init__.py", line 63, in on_event
    self._send_ifttt("op-"+event, makerkey, v1, v2, v3)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTTmaker/__init__.py", line 80, in _send_ifttt
    payload = "{ 'value1' : " + value1 + ", 'value2' : " + value2 + ", 'value3' : " + value3 + "}"
TypeError: coercing to Unicode: need string or buffer, float found`

**Comment by sedgett** [comment]
wrapped the use of float in str(); should resolve issue.
